(() => {
'use strict';
const SB='https://osyphouhtjanfoujcbid.supabase.co';
const KEY='sb_publishable_FJcKpYUD2sH6Ai2psVe97Q_59HenbRO';
const TK='menu-admin-token-v1', CK='menu-admin-client-v1';
const S={token:sessionStorage.getItem(TK)||'',days:7,data:null,selected:new Set(),q:'',cat:'',status:'',dragDish:null,dragCat:null};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0));
const money=n=>fmt(Math.round(Number(n||0)))+' ₸';
const localInput=v=>v?new Date(v).toISOString().slice(0,16):'';
const iso=v=>v?new Date(v).toISOString():null;
function clientKey(){let v=localStorage.getItem(CK);if(!v){v=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();localStorage.setItem(CK,v)}return v}
async function rpc(fn,body,skip){
  const r=await fetch(SB+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});
  const t=await r.text();let p=null;try{p=t?JSON.parse(t):null}catch{p=t}
  if(!r.ok){const m=(p&&p.message)||(p&&p.error)||(typeof p==='string'?p:'Ошибка запроса');if(!skip&&/ADMIN_SESSION_INVALID|invalid authorization specification/i.test(m))forceLogout('Сессия истекла. Войдите снова.');throw new Error(m)}
  return p
}
function toast(m,type){const n=document.createElement('div');n.className='toast'+(type==='error'?' error':'');n.textContent=m;$('#toastHost').appendChild(n);setTimeout(()=>n.remove(),3200)}
function saving(on,text){$('#saveIndicator').textContent=text||(on?'Сохраняем…':'Все изменения сохранены')}
function forceLogout(msg){S.token='';S.data=null;sessionStorage.removeItem(TK);$('#adminApp').hidden=true;$('#loginScreen').hidden=false;$('#loginPassword').value='';if(msg){$('#loginError').textContent=msg;$('#loginError').hidden=false}}
async function login(pass){const x=await rpc('admin_login',{p_password:pass,p_client_key:clientKey()},true);if(!x||!x.ok||!x.token)throw new Error(x&&x.error||'Не удалось войти');S.token=x.token;sessionStorage.setItem(TK,S.token);await boot()}
async function logout(){try{if(S.token)await rpc('admin_logout',{p_token:S.token},true)}catch{}forceLogout()}
async function mutate(a,p){saving(true);try{const x=await rpc('admin_mutate',{p_token:S.token,p_action:a,p_payload:p||{}});saving(false);return x}catch(e){saving(false,'Ошибка сохранения');throw e}}
async function load(days,silent){if(!silent)saving(true,'Загружаем данные…');try{const d=await rpc('admin_bootstrap',{p_token:S.token,p_days:days||S.days});S.data=d;S.days=Number(d.periodDays||days||7);renderAll();if(!silent)saving(false);return d}catch(e){if(!silent)saving(false,'Ошибка загрузки');throw e}}
async function boot(){$('#loginScreen').hidden=true;$('#adminApp').hidden=false;$('#loginError').hidden=true;await load(S.days)}
const META={dashboard:['Обзор','Главные показатели меню'],analytics:['Аналитика','Поведение посетителей'],dishes:['Блюда','Управление каталогом'],categories:['Категории','Структура меню'],recommendations:['Рекомендации','Ручные и автоматические подборки'],content:['Контент сайта','Контакты, график, адрес и тексты']};
function go(sec){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===sec));$$('.page-section').forEach(x=>x.classList.toggle('active',x.id==='section-'+sec));const m=META[sec]||['Админ-панель',''];$('#pageTitle').textContent=m[0];$('#pageSub').textContent=m[1];document.body.classList.remove('sidebar-open');scrollTo({top:0,behavior:'smooth'})}
function period(n){n=Number(n);if(!n||n===S.days)return;S.days=n;$$('[data-period-host] button').forEach(b=>b.classList.toggle('active',Number(b.dataset.days)===n));load(n).catch(e=>toast(e.message,'error'))}
function kpi(l,v,n){return '<div class="kpi-card"><div class="kpi-label">'+esc(l)+'</div><div class="kpi-value">'+esc(v)+'</div><div class="kpi-note">'+esc(n||'')+'</div></div>'}
function renderKpis(host,cart){const m=S.data&&S.data.analytics&&S.data.analytics.metrics||{};const a=cart?[['Открыли корзину',fmt(m.cart_open),'за период'],['Добавили товары',fmt(m.cart_add),'добавлений'],['Открыли оформление',fmt(m.checkout_open),'переход к данным'],['Средняя корзина',money(m.avg_cart_total),'перед оформлением']]:[['Посетители',fmt(m.visitors),'уникальные устройства'],['Просмотры блюд',fmt(m.product_view),'открытия карточек'],['Добавления в корзину',fmt(m.cart_add),'действия на сайте'],['Переходы в WhatsApp',fmt(m.whatsapp_click),(m.whatsapp_conversion||0)+'% от открытий меню']];host.innerHTML=a.map(x=>kpi(x[0],x[1],x[2])).join('')}
function chart(host){const d=S.data&&S.data.analytics&&S.data.analytics.byDay||[];if(!d.length){host.innerHTML='<div class="empty-state">Статистика появится после первых посещений меню.</div>';return}const w=700,h=220,p=24,max=Math.max(1,...d.map(x=>Math.max(Number(x.visitors||0),Number(x.views||0))));const xx=i=>p+(d.length===1?0:i*(w-p*2)/(d.length-1)), yy=v=>h-p-Number(v||0)*(h-p*2)/max;const pts=d.map((x,i)=>xx(i)+','+yy(x.visitors)).join(' '), area=p+','+(h-p)+' '+pts+' '+xx(d.length-1)+','+(h-p);const labs=d.map((x,i)=>i%Math.max(1,Math.ceil(d.length/6))===0?'<text class="chart-label" x="'+xx(i)+'" y="'+(h-4)+'" text-anchor="middle">'+esc(String(x.date).slice(5))+'</text>':'').join('');const dots=d.map((x,i)=>'<circle class="chart-dot" cx="'+xx(i)+'" cy="'+yy(x.visitors)+'" r="3"><title>'+esc(x.date)+': '+x.visitors+'</title></circle>').join('');host.innerHTML='<svg class="chart-svg" viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#202329" stop-opacity=".16"/><stop offset="1" stop-color="#202329" stop-opacity="0"/></linearGradient></defs><line class="chart-grid" x1="'+p+'" y1="'+(h-p)+'" x2="'+(w-p)+'" y2="'+(h-p)+'"/><line class="chart-grid" x1="'+p+'" y1="'+(h/2)+'" x2="'+(w-p)+'" y2="'+(h/2)+'"/><polygon class="chart-area" points="'+area+'"/><polyline class="chart-line" points="'+pts+'"/>'+dots+labs+'</svg>'}
function funnel(host,rows){rows=rows||S.data&&S.data.analytics&&S.data.analytics.funnel||[];const max=Math.max(1,...rows.map(x=>Number(x.value||0)));host.innerHTML=rows.map(r=>'<div class="funnel-row"><div class="funnel-label">'+esc(r.label)+'</div><div class="funnel-track"><div class="funnel-fill" style="width:'+Math.max(1,Number(r.value||0)/max*100)+'%"></div></div><div class="funnel-value">'+fmt(r.value)+'</div></div>').join('')||'<div class="empty-state">Пока нет данных.</div>'}
function score(r){return Number(r.whatsapp||0)*8+Number(r.cart_adds||0)*5+Number(r.favorites||0)*3+Number(r.views||0)}
function ranks(rows,val,sub,max){if(!rows||!rows.length)return '<div class="empty-state">Пока недостаточно данных.</div>';return rows.slice(0,max||6).map((r,i)=>'<div class="rank-item"><div class="rank-index">'+(i+1)+'</div><div class="rank-copy"><strong>'+esc(r.name||r.query||'—')+'</strong><span>'+esc(sub?sub(r):'')+'</span></div><div class="rank-value">'+esc(val(r))+'</div></div>').join('')}
function dashboard(){renderKpis($('#dashboardKpis'));chart($('#activityChart'));funnel($('#dashboardFunnel'));const st=[...(S.data.analytics.dishStats||[])].sort((a,b)=>score(b)-score(a));$('#dashboardTopDishes').innerHTML=ranks(st,r=>fmt(score(r)),r=>fmt(r.views)+' просмотров · '+fmt(r.cart_adds)+' в корзину');const d=S.data.dishes||[],c=S.data.categories||[],hidden=d.filter(x=>!x.is_available).length,scheduled=d.filter(x=>x.scheduled_price&&x.scheduled_price_at).length;const h=[['Всего блюд',d.length],['Опубликовано',d.length-hidden],['Скрыто',hidden],['Категорий',c.filter(x=>x.is_visible).length],['Рекомендуем',d.filter(x=>x.is_recommended).length],['Цены запланированы',scheduled]];$('#menuHealth').innerHTML=h.map(x=>'<div class="health-card"><strong>'+fmt(x[1])+'</strong><span>'+esc(x[0])+'</span></div>').join('')}
function bars(host,rows){const total=(rows||[]).reduce((s,x)=>s+Number(x.count||0),0);if(!total){host.innerHTML='<div class="empty-state">Пока нет данных.</div>';return}host.innerHTML=rows.map(r=>{const p=Math.round(Number(r.count||0)/total*100);return '<div><div class="stat-row-head"><span>'+esc(r.name)+'</span><strong>'+p+'%</strong></div><div class="stat-track"><div class="stat-fill" style="width:'+p+'%"></div></div></div>'}).join('')}
function analytics(){renderKpis($('#analyticsKpis'));renderKpis($('#cartKpis'),true);chart($('#analyticsChart'));funnel($('#analyticsFunnel'));funnel($('#cartFunnel'),(S.data.analytics.funnel||[]).filter(x=>['cart_add','checkout_open','whatsapp_click'].includes(x.key)));const st=S.data.analytics.dishStats||[];$('#dishAnalyticsBody').innerHTML=st.length?st.map(r=>'<tr><td><div class="product-copy"><strong>'+esc(r.name||'#'+r.product_id)+'</strong><span>'+esc(r.category||'')+'</span></div></td><td>'+fmt(r.views)+'</td><td>'+fmt(r.favorites)+'</td><td>'+fmt(r.cart_adds)+'</td><td>'+fmt(r.whatsapp)+'</td><td>'+Number(r.cart_conversion||0).toFixed(1)+'%</td></tr>').join(''):'<tr><td colspan="6"><div class="empty-state">Данные появятся после первых действий пользователей.</div></td></tr>';$('#searchRanking').innerHTML=ranks(S.data.analytics.searches||[],r=>fmt(r.count),()=> 'поисковых запросов',50);$('#categoryRanking').innerHTML=ranks(S.data.analytics.categories||[],r=>fmt(r.views),r=>fmt(r.cart_adds)+' добавлений в корзину',20);bars($('#deviceStats'),S.data.analytics.devices||[]);bars($('#browserStats'),S.data.analytics.browsers||[])}
function visible(d){if(!d.is_available)return false;const n=Date.now();if(d.hidden_from){const a=new Date(d.hidden_from).getTime(),b=d.hidden_until?new Date(d.hidden_until).getTime():Infinity;if(n>=a&&n<b)return false}return true}
function dishesFiltered(){const q=S.q.toLowerCase().trim();return (S.data.dishes||[]).filter(d=>(!q||String(d.name).toLowerCase().includes(q)||String(d.description||'').toLowerCase().includes(q))&&(!S.cat||d.category_id===S.cat)&&(!S.status||(S.status==='visible'&&visible(d))||(S.status==='hidden'&&!visible(d))||(S.status==='recommended'&&d.is_recommended)))}
function filters(){const el=$('#dishCategoryFilter'),v=el.value;el.innerHTML='<option value="">Все категории</option>'+(S.data.categories||[]).map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');el.value=v||S.cat}
function dishes(){filters();const rows=dishesFiltered();$('#dishesBody').innerHTML=rows.length?rows.map(d=>'<tr draggable="true" data-dish-id="'+d.id+'"><td class="check-col"><input type="checkbox" data-select-dish="'+d.id+'" '+(S.selected.has(d.id)?'checked':'')+'></td><td><div class="product-cell"><img class="product-thumb" src="'+esc(d.photo_url||'/api/branding?type=logo')+'" alt="" loading="lazy"><div class="product-copy"><strong>'+esc(d.name)+'</strong><span>#'+d.public_id+' · '+esc(d.weight||'без веса')+(d.scheduled_price?' · новая цена запланирована':'')+'</span></div></div></td><td>'+esc(d.category_name||'')+'</td><td><strong>'+money(d.price)+'</strong>'+(d.scheduled_price?'<div class="kpi-note">→ '+money(d.scheduled_price)+'</div>':'')+'</td><td><button class="status-switch '+(d.is_available?'on':'')+'" data-toggle-dish="'+d.id+'"></button></td><td><button class="status-switch '+(d.is_recommended?'on':'')+'" data-rec-dish="'+d.id+'"></button></td><td><div class="row-actions"><button class="small-action" data-copy-dish="'+d.id+'">Копия</button><button class="small-action" data-edit-dish="'+d.id+'">Изменить</button></div></td></tr>').join(''):'<tr><td colspan="7"><div class="empty-state">Ничего не найдено.</div></td></tr>';bulk();bindDishRows()}
function findDish(id){return (S.data.dishes||[]).find(x=>x.id===id)}
function findCat(id){return (S.data.categories||[]).find(x=>x.id===id)}
function bulk(){$('#bulkCount').textContent=S.selected.size;$('#bulkBar').hidden=!S.selected.size;const f=dishesFiltered();$('#selectAllDishes').checked=f.length>0&&f.every(d=>S.selected.has(d.id))}
function bindDishRows(){
  $$('[data-select-dish]').forEach(i=>i.onchange=()=>{i.checked?S.selected.add(i.dataset.selectDish):S.selected.delete(i.dataset.selectDish);bulk()});
  $$('[data-toggle-dish]').forEach(b=>b.onclick=async()=>{const d=findDish(b.dataset.toggleDish);try{await mutate('toggle_dish',{id:d.id,is_available:!d.is_available});toast(d.is_available?'Блюдо скрыто':'Блюдо опубликовано');await load(S.days,true)}catch(e){toast(e.message,'error')}});
  $$('[data-rec-dish]').forEach(b=>b.onclick=async()=>{const d=findDish(b.dataset.recDish);try{await mutate('set_recommended',{id:d.id,is_recommended:!d.is_recommended});toast(d.is_recommended?'Убрано из «Рекомендуем»':'Добавлено в «Рекомендуем»');await load(S.days,true)}catch(e){toast(e.message,'error')}});
  $$('[data-edit-dish]').forEach(b=>b.onclick=()=>dishModal(findDish(b.dataset.editDish)));
  $$('[data-copy-dish]').forEach(b=>b.onclick=async()=>{try{await mutate('duplicate_dish',{id:b.dataset.copyDish});toast('Копия создана и скрыта');await load(S.days,true)}catch(e){toast(e.message,'error')}});
  $$('#dishesBody tr[draggable=true]').forEach(r=>{r.ondragstart=()=>{S.dragDish=r.dataset.dishId;r.classList.add('dragging')};r.ondragend=()=>{S.dragDish=null;r.classList.remove('dragging')};r.ondragover=e=>e.preventDefault();r.ondrop=async e=>{e.preventDefault();const a=S.dragDish,b=r.dataset.dishId;if(!a||a===b)return;const all=[...S.data.dishes],from=all.findIndex(x=>x.id===a),to=all.findIndex(x=>x.id===b);if(from<0||to<0)return;const mv=all.splice(from,1)[0];all.splice(to,0,mv);S.data.dishes=all;dishes();try{await mutate('reorder_dishes',{ids:all.map(x=>x.id)});toast('Порядок сохранён');await load(S.days,true)}catch(err){toast(err.message,'error')}}})
}
function categories(){const cats=S.data.categories||[];$('#categoriesList').innerHTML=cats.map(c=>{const n=(S.data.dishes||[]).filter(d=>d.category_id===c.id).length;return '<div class="category-row" draggable="true" data-category-id="'+c.id+'"><div class="drag-handle">⋮⋮</div><div class="category-copy"><strong>'+esc(c.name)+'</strong><span>'+n+' блюд · '+esc(c.slug||'')+'</span></div><button class="status-switch '+(c.is_visible?'on':'')+'" data-toggle-cat="'+c.id+'"></button><button class="small-action" data-edit-cat="'+c.id+'">Изменить</button></div>'}).join('');$$('[data-toggle-cat]').forEach(b=>b.onclick=async()=>{const c=findCat(b.dataset.toggleCat);try{await mutate('toggle_category',{id:c.id,is_visible:!c.is_visible});toast(c.is_visible?'Категория скрыта':'Категория опубликована');await load(S.days,true)}catch(e){toast(e.message,'error')}});$$('[data-edit-cat]').forEach(b=>b.onclick=()=>catModal(findCat(b.dataset.editCat)));$$('#categoriesList [draggable=true]').forEach(r=>{r.ondragstart=()=>{S.dragCat=r.dataset.categoryId;r.classList.add('dragging')};r.ondragend=()=>{S.dragCat=null;r.classList.remove('dragging')};r.ondragover=e=>e.preventDefault();r.ondrop=async e=>{e.preventDefault();const a=S.dragCat,b=r.dataset.categoryId;if(!a||a===b)return;const all=[...S.data.categories],from=all.findIndex(x=>x.id===a),to=all.findIndex(x=>x.id===b);const mv=all.splice(from,1)[0];all.splice(to,0,mv);S.data.categories=all;categories();try{await mutate('reorder_categories',{ids:all.map(x=>x.id)});toast('Порядок категорий сохранён');await load(S.days,true)}catch(err){toast(err.message,'error')}}})}
function recommendations(){const d=S.data.dishes||[];$('#manualRecommendations').innerHTML=d.map(x=>'<div class="recommend-row"><img src="'+esc(x.photo_url||'/api/branding?type=logo')+'" alt="" loading="lazy"><div><strong>'+esc(x.name)+'</strong><span>'+esc(x.category_name||'')+' · '+money(x.price)+'</span></div><button class="status-switch '+(x.is_recommended?'on':'')+'" data-r-toggle="'+x.id+'"></button></div>').join('');$$('[data-r-toggle]').forEach(b=>b.onclick=async()=>{const d=findDish(b.dataset.rToggle);try{await mutate('set_recommended',{id:d.id,is_recommended:!d.is_recommended});toast(d.is_recommended?'Убрано':'Добавлено в «Рекомендуем»');await load(S.days,true)}catch(e){toast(e.message,'error')}})}
function settings(){const s=S.data.settings||{},f=$('#settingsForm'),names=['restaurant_name','subtitle','city','schedule_open','schedule_close','delivery_text','free_delivery_from','whatsapp_number','phone_number','instagram_handle','instagram_url','address_text','map_url','map_embed_url','logo_url','banner_url','contact_button_text','whatsapp_order_title'];names.forEach(n=>{if(f.elements[n])f.elements[n].value=s[n]==null?'':s[n]});f.elements.popular_fallback_names.value=Array.isArray(s.popular_fallback_names)?s.popular_fallback_names.join('\n'):''}
function renderAll(){dashboard();analytics();dishes();categories();recommendations();settings();$$('[data-period-host] button').forEach(b=>b.classList.toggle('active',Number(b.dataset.days)===S.days))}
function openModal(id){$('#'+id).hidden=false;document.body.style.overflow='hidden'}
function closeModal(id){$('#'+id).hidden=true;document.body.style.overflow=''}
function preview(){const f=$('#dishForm'),name=f.elements.name.value||'Название блюда',price=f.elements.price.value||0,img=f.elements.detail_image_url.value||f.elements.photo_url.value||'/api/branding?type=banner',desc=f.elements.description.value||'Описание и состав блюда будут показаны здесь.',w=f.elements.weight.value||'';$('#dishPreview').innerHTML='<div class="preview-card"><img src="'+esc(img)+'" alt=""><div class="preview-card-copy"><h3>'+esc(name)+'</h3>'+(w?'<div class="kpi-note">'+esc(w)+'</div>':'')+'<p>'+esc(desc)+'</p><div class="preview-price">'+money(price)+'</div></div></div>'}
function history(d){const box=$('#priceHistoryBox');if(!d){box.hidden=true;return}box.hidden=false;const r=(S.data.priceHistory||[]).filter(x=>x.dish_id===d.id);$('#priceHistoryList').innerHTML=r.length?r.map(x=>'<div class="history-item"><span>'+new Date(x.changed_at).toLocaleString('ru-RU')+'</span><strong>'+(x.old_price==null?'—':money(x.old_price))+' → '+money(x.new_price)+'</strong></div>').join(''):'<div class="empty-state">Цена ещё не менялась.</div>'}
function dishModal(d){const f=$('#dishForm');f.reset();f.elements.category_id.innerHTML=(S.data.categories||[]).map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');const x=d||{id:'',name:'',category_id:S.data.categories&&S.data.categories[0]&&S.data.categories[0].id||'',price:'',old_price:'',weight:'',description:'',photo_url:'',detail_image_url:'',is_available:true,is_recommended:false};['id','name','category_id','price','old_price','weight','description','photo_url','detail_image_url'].forEach(n=>f.elements[n].value=x[n]==null?'':x[n]);f.elements.is_available.checked=x.is_available!==false;f.elements.is_recommended.checked=!!x.is_recommended;f.elements.hidden_from.value=localInput(x.hidden_from);f.elements.hidden_until.value=localInput(x.hidden_until);$('#dishModalTitle').textContent=d?'Изменить блюдо':'Новое блюдо';$('#dishModalSub').textContent=d?'#'+x.public_id+' · '+(x.category_name||''):'Заполните карточку блюда';$('#schedulePriceValue').value=x.scheduled_price||'';$('#schedulePriceDate').value=localInput(x.scheduled_price_at);$('#scheduledPriceStatus').textContent=x.scheduled_price&&x.scheduled_price_at?money(x.scheduled_price)+' · '+new Date(x.scheduled_price_at).toLocaleString('ru-RU'):'Не запланирована';$('#cancelScheduledPriceBtn').hidden=!(x.scheduled_price&&x.scheduled_price_at);$('#scheduledPriceBox').hidden=!d;history(d);preview();openModal('dishModal')}
async function saveDish(){const f=$('#dishForm'),fd=new FormData(f),p={id:fd.get('id')||null,name:fd.get('name'),category_id:fd.get('category_id'),price:Number(fd.get('price')||0),old_price:fd.get('old_price')===''?null:Number(fd.get('old_price')),weight:fd.get('weight')||null,description:fd.get('description')||null,photo_url:fd.get('photo_url')||null,detail_image_url:fd.get('detail_image_url')||null,hidden_from:iso(fd.get('hidden_from')),hidden_until:iso(fd.get('hidden_until')),is_available:f.elements.is_available.checked,is_recommended:f.elements.is_recommended.checked};await mutate('save_dish',p);closeModal('dishModal');toast('Блюдо сохранено');await load(S.days,true)}
function catModal(c){const f=$('#categoryForm');f.reset();f.elements.id.value=c&&c.id||'';f.elements.name.value=c&&c.name||'';f.elements.slug.value=c&&c.slug||'';f.elements.is_visible.checked=c?c.is_visible!==false:true;$('#categoryModalTitle').textContent=c?'Изменить категорию':'Новая категория';openModal('categoryModal')}
async function saveCat(){const f=$('#categoryForm');await mutate('save_category',{id:f.elements.id.value||null,name:f.elements.name.value,slug:f.elements.slug.value,is_visible:f.elements.is_visible.checked});closeModal('categoryModal');toast('Категория сохранена');await load(S.days,true)}
async function schedule(){const id=$('#dishForm').elements.id.value,p=Number($('#schedulePriceValue').value),d=$('#schedulePriceDate').value;if(!id||!Number.isFinite(p)||p<0||!d){toast('Укажите новую цену и дату','error');return}await mutate('schedule_price',{id:id,new_price:p,apply_at:new Date(d).toISOString()});toast('Изменение цены запланировано');await load(S.days,true);dishModal(findDish(id))}
async function cancelSchedule(){const id=$('#dishForm').elements.id.value;if(!id)return;await mutate('cancel_scheduled_price',{id:id});toast('Отложенная цена отменена');await load(S.days,true);dishModal(findDish(id))}
async function saveSettings(){const f=$('#settingsForm'),p={},names=['restaurant_name','subtitle','city','schedule_open','schedule_close','delivery_text','free_delivery_from','whatsapp_number','phone_number','instagram_handle','instagram_url','address_text','map_url','map_embed_url','logo_url','banner_url','contact_button_text','whatsapp_order_title'];names.forEach(n=>p[n]=f.elements[n].value);p.popular_fallback_names=f.elements.popular_fallback_names.value.split('\n').map(x=>x.trim()).filter(Boolean);await mutate('save_settings',p);toast('Контент сайта сохранён');await load(S.days,true)}
async function bulkPrice(){const f=$('#bulkPriceForm');await mutate('batch_price',{ids:Array.from(S.selected),mode:f.elements.mode.value,value:Number(f.elements.value.value)});closeModal('bulkPriceModal');S.selected.clear();toast('Цены обновлены');await load(S.days,true)}
function init(){
  $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').hidden=true;$('#loginBtn').disabled=true;try{await login($('#loginPassword').value)}catch(x){$('#loginError').textContent=x.message;$('#loginError').hidden=false}finally{$('#loginBtn').disabled=false}};
  $('#logoutBtn').onclick=logout;$('#refreshBtn').onclick=()=>load(S.days).then(()=>toast('Данные обновлены')).catch(e=>toast(e.message,'error'));
  $('#menuToggle').onclick=()=>document.body.classList.add('sidebar-open');$('#sidebarClose').onclick=()=>document.body.classList.remove('sidebar-open');
  $$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.section));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-period-host] button').forEach(b=>b.onclick=()=>period(b.dataset.days));
  $$('[data-analytics-tab]').forEach(b=>b.onclick=()=>{$$('[data-analytics-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-pane]').forEach(x=>x.classList.toggle('active',x.dataset.pane===b.dataset.analyticsTab))});
  $('#dishSearch').oninput=e=>{S.q=e.target.value;dishes()};$('#dishCategoryFilter').onchange=e=>{S.cat=e.target.value;dishes()};$('#dishStatusFilter').onchange=e=>{S.status=e.target.value;dishes()};
  $('#newDishBtn').onclick=()=>dishModal();$('#newCategoryBtn').onclick=()=>catModal();
  $('#selectAllDishes').onchange=e=>{const r=dishesFiltered();if(e.target.checked)r.forEach(d=>S.selected.add(d.id));else r.forEach(d=>S.selected.delete(d.id));dishes()};
  $('#bulkClearBtn').onclick=()=>{S.selected.clear();dishes()};$('#bulkPriceBtn').onclick=()=>{$('#bulkPriceForm').reset();openModal('bulkPriceModal')};
  $('#dishForm').onsubmit=e=>{e.preventDefault();saveDish().catch(x=>toast(x.message,'error'))};$('#dishForm').oninput=preview;
  $('#categoryForm').onsubmit=e=>{e.preventDefault();saveCat().catch(x=>toast(x.message,'error'))};$('#bulkPriceForm').onsubmit=e=>{e.preventDefault();bulkPrice().catch(x=>toast(x.message,'error'))};$('#settingsForm').onsubmit=e=>{e.preventDefault();saveSettings().catch(x=>toast(x.message,'error'))};
  $('#schedulePriceBtn').onclick=()=>schedule().catch(e=>toast(e.message,'error'));$('#cancelScheduledPriceBtn').onclick=()=>cancelSchedule().catch(e=>toast(e.message,'error'));
  $$('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));$$('.modal-backdrop').forEach(m=>m.onmousedown=e=>{if(e.target===m)closeModal(m.id)});
  document.onkeydown=e=>{if(e.key==='Escape'){const m=$$('.modal-backdrop').find(x=>!x.hidden);if(m)closeModal(m.id);else document.body.classList.remove('sidebar-open')}};
}
init();if(S.token)boot().catch(e=>forceLogout(e.message));
})();